/*
 * CFD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CartApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CartApiTests
    {
        private CartApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CartApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOf(typeof(CartApi), instance);
        }

        
        /// <summary>
        /// Test AddCartItem
        /// </summary>
        [Test]
        public void AddCartItemTest()
        {
            MenuItem menuItem = new MenuItem(1, "testing", "test", 10, 0);
            instance.AddCartItem(menuItem);
            
        }
        
        /// <summary>
        /// Test DeleteCartItem
        /// </summary>
        [Test]
        public void DeleteCartItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int itemId = null;
            //instance.DeleteCartItem(itemId);
            
        }
        
        /// <summary>
        /// Test ListCart
        /// </summary>
        [Test]
        public void ListCartTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //var response = instance.ListCart(limit);
            //Assert.IsInstanceOf(typeof(List<MenuItem>), response, "response is List<MenuItem>");
        }
        
    }

}
